<?php

$title = 'Add new Task';
$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php

$form->setAttribute('action', $this->url('task', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div>

    <?php
        echo $this->formRow($form->get('title'));
    ?>

</div>
<div>

    <?php
        echo $this->formRow($form->get('description'));
    ?>

</div>

<div>

    <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>

</div>