<?php

$title = 'Edit task';
$this->headTitle($title);

?>

<h1>
    <?= $this->escapeHtml($title) ?>
</h1>

<?php

$task = $form->get('title');
$task->setAttribute('class', 'form-control');
$task->setAttribute('placeholder', 'Task title');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'Status');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php $this->formLabel($task) ?>
    <?php $this->formElement($task) ?>
    <?php $this->formElementErrors()->render($task, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?php $this->formLabel($description) ?>
    <?php $this->formElement($description) ?>
    <?php $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <label for="status">Task status:</label>
    <label for="pending">Pending</label>
    <input id="pending" name="status" type="radio" value="0" <?php if($form->get('status') == 0){ echo "checked";} ?>>
    <label for="completed">Completed</label>
    <input id="completed" name="status" type="radio" value="1" <?php if($form->get('status') == 1){ echo "checked";} ?>>
</div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();